# Generated by Django 6.0.1 on 2026-02-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customuser_phone_remove_customuser_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=20),
        ),
    ]
