# Generated by Django 6.0.1 on 2026-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('RENTED', 'Rented'), ('RETURNED', 'Returned')], default='RENTED', max_length=20),
        ),
    ]
