# Generated by Django 6.0.1 on 2026-02-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental', '0002_alter_rental_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='return_date',
        ),
    ]
