# Generated by Django 6.0.1 on 2026-02-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental', '0003_remove_rental_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='total_copies',
        ),
    ]
